### ISSUE TITLE
Gateway IP GSM Modem connections without PIN/MSC#

### ISSUE THREAD

**Issue by glend1** [tdelenikas/smslib#10]
Im trying to create a Gateway connection using an IP GSM Modem, however it doesn't require a pin and i don't know how to find out the MSC#, and I don't know what "AA" refer to. it looks like it might be "memoryLocations" but i don't know what that means either.

I have looked at the example [here](https://github.com/smslib/smslib/blob/dev/smslib/src/test/java/org/smslib/Test_IPModem.java) and i am trying to connect using a similar method

``` java
import org.smslib.Service;
import org.smslib.gateway.modem.Modem;
import org.smslib.message.OutboundMessage;

public class SendSms {
    public SendSms() {
        Modem gateway = new Modem("modem", "host", "4001", "0000", "0000", null, "AA");
        Service.getInstance().start();
        Service.getInstance().registerGateway(gateway);
        System.out.println(gateway.getDeviceInformation());
        OutboundMessage message = new OutboundMessage("number", "Sending test.");
        Service.getInstance().send(message);
        Service.getInstance().stop();
        Service.getInstance().terminate();
    };
}
```

i believe this is because it is not connecting to the modem.

``` java
System.out.println(gateway.getDeviceInformation());
```

returns

```
MANUF:Sierra Wireless, MODEL:WMP100 Product, SERNO:N/A, IMSI:N/A, SW:N/A, RSSI:0dBm, MODE:null
```

i am certain that the ip and port are correct but i don't know how to check where the connection is failing.

**Comment by tdelenikas** [comment]
Start by setting PIN and PIN2 to "" (i.e. empty string)
Replace "AA" with "SM" - this usually works with most modems.
You can find the SMSC number from your SIM provider. Check your cellular provider or check another phone that has a SIM from the same provider.
