### ISSUE TITLE
SMSlib Documentation update

### ISSUE THREAD

**Issue by keerthivasan-r** [tdelenikas/smslib#13]
Hi, First of all, I thank you for the wonderful work. I would like to take it to your notice that JSMPP version has to be updated to v2.2.1, but its mentioned as jsmpp-2.1.0.jar in the documentation. Please update. Thanks

**Comment by tdelenikas** [comment]
Hello,

The new JSMPP is here: https://github.com/opentelecoms-org/jsmpp (http://jsmpp.org/)

There have been some fault reports about the latest JSMPP version. Reverting to the old version seems to solve them, but I cannot confirm this - it's based on one or two friends' feedback.

Thank you.
