### ISSUE TITLE
deleteMessagesAfterCallback accessible via runtime option

### ISSUE THREAD

**Issue by taufikterdidik** [tdelenikas/smslib#3]
I think deleteMessagesAfterCallback can be accessibe via runtime option, or, must I modifying code in SMSServer and i compile myself?

**Comment by tdelenikas** [comment]
No, there is no such runtime option yet.

Since you've mentioned it, I am keeping this ticket open as an enhancement request. All options in Settings.java will be converted to runtime options.

**Comment by tdelenikas** [comment]
http://smslib.org/maven2/snapshots/ updated.
