### ISSUE TITLE
Port on mac osx

### ISSUE THREAD

**Issue by vineetchaudhary** [tdelenikas/smslib#4]
A serial port on OSX is generally depicted as /dev/tty.devmaufacturer-version
To be precise in my case it is /dev/tty.HUAWEIMobile-Modem
But if I enter this as a port in Modem class then this is assumed as an IP address rather than a serial port because of the function isPortAnIpAddress
private boolean isPortAnIpAddress(String address)
{
if (address.indexOf('.') >= 0) return true;
return false;
}
Since this is treated as an ip address, the application fails to start.

**Comment by tdelenikas** [comment]
This should fix it. Maven snapshot updated. Thanks!
