### ISSUE TITLE
Use SLF4J (logback) for logging

### ISSUE THREAD

**Issue by danbst** [tdelenikas/smslib#8]
I have project that uses SLF4j (logback) for logging. Would be great if new version will use this new logging framework

**Comment by tdelenikas** [comment]
Have you spotted any weird code inside SMSLib?
I am asking because SMSLib v4 already uses slf4j...

**Comment by danbst** [comment]
Ah, I thought I was commenting on smslib-v3 and hadn't checked what's on in v4!
